Ot285 84 members service
alkemyTech/OT285-client pull request #51
Opened 2022-09-02 16:59 UTC by GastionG

2022-09-02 18:51 UTC, carolinalaborde requested changes

2022-09-02 18:51 UTC, carolinalaborde commented on src/app/features/pages/members/members.service.ts
> +}
MemberRes y memberRes son iguales excepto porque data puede tener un array o un objeto
Podes usar MemberRes y que data pueda tener un array o un objeto
data: Member[] | Member

2022-09-02 18:51 UTC, carolinalaborde commented on src/app/features/pages/members/members.service.ts
> +}
Por convención las interfaces deben usar pascal case

2022-09-02 18:51 UTC, carolinalaborde commented on src/app/features/pages/members/members.service.ts
> +
Los nombres deberian ser mas descriptivos. 
Un post realiza un create, un put un update, etc

2022-09-02 19:47 UTC, GastionG commented on src/app/features/pages/members/members.service.ts
> +
deberia haber metodos mas especificos? 
un getAll para pedir todos los miembros y otro get que use un id para pedir solo un miembro o el get que ya esta es mejor?

2022-09-02 19:47 UTC, GastionG commented on src/app/features/pages/members/members.service.ts
> +
el put y post si los voy a cambiar a update y create

2022-09-03 16:06 UTC, carolinalaborde approved these changes

2022-09-03 16:06 UTC, merged